language: generic
sudo: required
services:
  - docker

jobs:
  include:
    - stage: website
      before_install:
        - cd src/website
        - docker build -t projectgem/website .
      script:
        - docker images
      after_success:
        - if [ "$TRAVIS_BRANCH" == "spencer.infra.pipeline" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push projectgem/website; fi 
