language: node_js
node_js:
  - '8.12'
env:
  - NODE_ENV=travis
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - sudo -u postgres psql -c 'create database jumbosmash_test;' -U postgres
  - sudo -u postgres psql -c 'create extension if not exists citext;' -U postgres
script:
  - cd ./src/server
  - npm test
