language: node_js
node_js:
  - '8.12'
env:
  - NODE_ENV=travis
services:
  - postgresql
addons:
  postgresql: "10.5"
before_script:
  - psql -c 'create database jumbosmash_test;' -U postgres
  - psql -c 'create extension if not exists citext;' -U postgres
script:
  - cd ./src/server
