
language: node_js
node_js:
  - "8.12"
cache: npm
env:
  global:
    - NODE_CONFIG_ENV=travis
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
install:
  - npm install
  - cd ./src/mobile
  - npm install
  - cd ../..
  - cd ./src/koh
  - npm install
  - cd ../../src/server
  - npm install
before_script:
  - sudo -u postgres psql -c 'create database jumbosmash_test;' -U postgres
  - sudo -u postgres psql -d jumbosmash_test -c 'create extension if not exists citext;' -U postgres
  - npm run migrate up
script:
  - npm run lint
  - cd ../..
  - npm run flow
  - cd src/server
  - npm run check-env
  - npm run test
