language: generic
sudo: required
services:
  - docker

jobs:
  include:
    - stage: website
      before_install:
        - cd src/website
        - docker build -t sperrys/website:master .
      script:
        - docker images
      after_success:
        - if [ "$TRAVIS_BRANCH" == "spencer.infra.pipeline" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push sperrys/website:master; fi
    - stage: server
      dist: xenial
      language: node_js
      node_js:
        - "8.12"
      env:
        global:
          - NODE_CONFIG_ENV=travis
          - PGUSER=postgres
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
      services:
        - postgresql
      before_install:
        - sudo service postgresql stop
        - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
        - sudo chown postgres postgresql.conf
        - sudo mv postgresql.conf /etc/postgresql/10/main
        - sudo service postgresql start 10
      install:
        - npm install
        - ls ./src
        - ls ./src/koh
        - npm install --prefix ./src/koh
        - npm install --prefix ./src/mobile
        - npm install --prefix ./src/server
      before_script:
        - psql -c 'create database jumbosmash_test;' -U postgres
        - psql -d jumbosmash_test -c 'create extension if not exists citext;' -U postgres
        - cd ./src/server && npm run migrate up
      script:
        - npm run lint
        - cd ../..
        - npm run flow
        - cd src/server
        - npm run check-env
        - npm run test
