language: generic
sudo: required
services:
- docker
jobs:
  include:
  - stage: server
    dist: xenial
    language: node_js
    node_js:
      - '8.12'
    env:
      - NODE_CONFIG_ENV=travis
      - PGUSER=postgres
      - CHANGED=false
    cache:
      - npm
    addons:
       postgresql: '10'
    before_install:
      - if git diff --name-only HEAD^ | grep "src/server/";  then
          echo "Changes to Server Code, Continuing Travis Stage!";
        else
          echo "No Changes to Server, Exiting Stage ...!";
          travis_terminate 0;
        fi
    install:
      - echo "Installing Server Dependencies.." ;
      - npm install --prefix ./src/server
    before_script:
      - psql -c 'create database jumbosmash_test;' -U postgres
      - psql -d jumbosmash_test -c 'create extension if not exists citext;' -U postgres
      - cd ./src/server && npm run migrate up
    script:
      - npm run lint
      - cd ../..
      -`npx flow check --ignore ".*/src/deploy/*, .*/src/mobile/*""
      - cd src/server
      - npm run check-env
      - npm run test
notifications:
  slack:
    secure: BT+I+DPQBPupDHMADVKtE7QPkqpDpchMS9eLxrGqNc7WuND8dnce/p0/PpodbSOiBTlgoxaGj0iFg1rSf3Z6dOiLcJs4RuuY4hRVxto2nlznOnY4xHY8gHMvaWUy7JkIXeLKLRQ4+jXHvhVU8h1y+GvxHL2VmDlxYWWKlw/r1ltHi7/fDObIhEDQx6Da/pdqfVPpQAkBaPnF+z0I3ZqFh2f1TIMknn3SPDTHqbseioVc4BD9lceICQ+h82a2eQF9QTyYbBkeCk2rA4kfaA3zNmaDTpbApuYzryjtgAtyhowRngU4k9OCSFYJ8VVUGFDpAchakRffCvHMN0uf2UUtL0lZRL3Dre00bTTvwFNSH7ZRL7czUb0Fdr9NMyf6JS99ijVRb2LTsdf3aEgRgu/uq0zgca3vM1J28ZzZ5BBJvzezp6G9ia5m102CJ1Pcjspc8wUmcHw0YhKAsNBVzJWTW4JXkcoN0o/t04Y+QkESOrQ37uS+8WeaOZYK0AWos05Owd2AVJXk5oZBvqMxSNGSqn7qP6MgxV1gxi4A3qotWIr6kRfgO1qGdDthnyZMyPKfcH8eDDc18vWGPmDSkU5c4kMm28Poyv7Ne2CrWGcsTHJzrKdnNtpCCcnpZqRnTNgiotSfaEbCS21r4JP4E40Dz7FilJ//zkPdoNi361AJ1+U=
