// @flow
import type { Dispatch } from 'redux';

// SHARED
export const SERVER_ERROR = 'SERVER_ERROR';
export const BAD_REQUEST = 'BAD_REQUEST';
export const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
export const TIMEOUT = 'TIMEOUT'

// AUTH
export const SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND';
export const SEND_VERIFICATION_EMAIL__UTLN_NOT_2019 = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_2019';
