// @flow

// SHARED
const SERVER_ERROR = 'SERVER_ERROR';
const BAD_REQUEST = 'BAD_REQUEST';
const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';

// AUTH

// Send Verification Email
const SEND_VERIFICATION_EMAIL__SUCESS = 'SEND_VERIFICATION_EMAIL__SUCESS';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_2019 = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_2019';

// Verify
const VERIFY__SUCCESS = 'VERIFY__SUCCESS';
const VERIFY__BAD_CODE = 'VERIFY__BAD_CODE';
const VERIFY__EXPIRED_CODE = 'VERIFY__EXPIRED_CODE';
const VERIFY__NO_EMAIL_SENT = 'VERIFY__NO_EMAIL_SENT';

module.exports = {
  // Shared
  SERVER_ERROR,
  BAD_REQUEST,
  TOO_MANY_REQUESTS,

  // AUTH
  // Send Verification Email
  SEND_VERIFICATION_EMAIL__SUCESS,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_2019,

  // Verify
  VERIFY__SUCCESS,
  VERIFY__BAD_CODE,
  VERIFY__EXPIRED_CODE,
  VERIFY__NO_EMAIL_SENT,
};
