// @flow

// SHARED
const SERVER_ERROR = 'SERVER_ERROR';
const BAD_REQUEST = 'BAD_REQUEST';
const AUTHORIZED = 'AUTHORIZED';
const UNAUTHORIZED = 'UNAUTHORIZED';
const PROFILE_SETUP_INCOMPLETE = 'PROFILE_SETUP_INCOMPLETE';
// AUTH

// Send Verification Email
const SEND_VERIFICATION_EMAIL__SUCCESS = 'SEND_VERIFICATION_EMAIL__SUCCESS';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_2019 = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_2019';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_STUDENT = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_STUDENT';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_UNDERGRAD = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_UNDERGRAD';
const SEND_VERIFICATION_EMAIL__EMAIL_ALREADY_SENT = 'SEND_VERIFICATION_EMAIL__EMAIL_ALREADY_SENT';

// Verify
const VERIFY__SUCCESS = 'VERIFY__SUCCESS';
const VERIFY__BAD_CODE = 'VERIFY__BAD_CODE';
const VERIFY__EXPIRED_CODE = 'VERIFY__EXPIRED_CODE';
const VERIFY__NO_EMAIL_SENT = 'VERIFY__NO_EMAIL_SENT';

// USERS

// Create Profile
const CREATE_PROFILE__SUCCESS = 'CREATE_PROFILE__SUCCESS';
const CREATE_PROFILE__PROFILE_ALREADY_CREATED = 'CREATE_PROFILE__PROFILE_ALREADY_CREATED';
const CREATE_PROFILE__INVALID_REQUEST = 'CREATE_PROFILE__INVALID_REQUEST';
const CREATE_PROFILE__PHOTO_REQUIRED = 'CREATE_PROFILE__PHOTO_REQUIRED';

// Update Profile
const UPDATE_PROFILE__SUCCESS = 'UPDATE_PROFILE__SUCCESS';
const UPDATE_PROFILE__INVALID_REQUEST = 'UPDATE_PROFILE__INVALID_REQUEST';

// Get profile
const GET_PROFILE__SUCCESS = 'GET_PROFILE__SUCCESS';
const GET_PROFILE__PROFILE_NOT_FOUND = 'GET_PROFILE__PROFILE_NOT_FOUND';
const GET_PROFILE__BAD_USER_ID = 'GET_PROFILE__BAD_USER_ID';

// Get Scene Candidates
const GET_SCENE_CANDIDATES__SUCCESS = 'GET_SCENE_CANDIDATES__SUCCESS';
const GET_SCENE_CANDIDATES__INVALID_SCENE = 'GET_SCENE_CANDIDATES__INVALID_SCENE';

// Get Matches
const GET_MATCHES__SUCCESS = 'GET_MATCHES__SUCCESS';

// Judge
const JUDGE__SUCCESS = 'JUDGE__SUCCESS';
const JUDGE__CANDIDATE_NOT_FOUND = 'JUDGE__CANDIDATE_NOT_FOUND';

// Block
const BLOCK__SUCCESS = 'BLOCK__SUCCESS';
const BLOCK__USER_NOT_FOUND = 'BLOCK__USER_NOT_FOUND';

// Update Settings
const UPDATE_SETTINGS__SUCCESS = 'UPDATE_SETTINGS__SUCCESS';

// Get Settings
const GET_SETTINGS__SUCCESS = 'GET_SETTINGS__SUCCESS';

// PHOTOS
// Sign Url
const SIGN_URL__SUCCESS = 'SIGN_URL__SUCCESS';

// Get Photo
const GET_PHOTO__NOT_FOUND = 'GET_PHOTO__NOT_FOUND';

// Confirm Upload
const CONFIRM_UPLOAD__SUCCESS = 'CONFIRM_UPLOAD__SUCCESS';
const CONFIRM_UPLOAD__NO_UNCONFIRMED_PHOTO = 'CONFIRM_UPLOAD__NO_UNCONFIRMED_PHOTO';
const CONFIRM_UPLOAD__NO_UPLOAD_FOUND = 'CONFIRM_UPLOAD__NO_UPLOAD_FOUND';
const CONFIRM_UPLOAD__NO_AVAILABLE_SLOT = 'CONFIRM_UPLOAD__NO_AVAILABLE_SLOT';

// Delete Photo
const DELETE_PHOTO__SUCCESS = 'DELETE_PHOTO__SUCCESS';
const DELETE_PHOTO__CANNOT_DELETE_LAST_PHOTO = 'DELETE_PHOTO__CANNOT_DELETE_LAST_PHOTO';
const DELETE_PHOTO__NOT_FOUND = 'DELETE_PHOTO__NOT_FOUND';

// Reorder Photos
const REORDER_PHOTOS__SUCCESS = 'REORDER_PHOTOS__SUCCESS';
const REORDER_PHOTOS__MISMATCHED_IDS = 'REORDER_PHOTOS__MISMATCHED_IDS';

// MESSAGES
// Send Message
const SEND_MESSAGE__SUCCESS = 'SEND_MESSAGE__SUCCESS';
const SEND_MESSAGE__USER_NOT_FOUND = 'SEND_MESSAGE__USER_NOT_FOUND';

// Get Conversation
const GET_CONVERSATION__SUCCESS = 'GET_CONVERSATION__SUCCESS';
const GET_CONVERSATION__INVALID_MOST_RECENT_MESSAGE_ID = 'GET_CONVERSATION__INVALID_MOST_RECENT_MESSAGE_ID';

module.exports = {
  // Shared
  SERVER_ERROR,
  BAD_REQUEST,
  AUTHORIZED,
  UNAUTHORIZED,
  PROFILE_SETUP_INCOMPLETE,
  // AUTH
  // Send Verification Email
  SEND_VERIFICATION_EMAIL__SUCCESS,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_2019,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_UNDERGRAD,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_STUDENT,
  SEND_VERIFICATION_EMAIL__EMAIL_ALREADY_SENT,

  // Verify
  VERIFY__SUCCESS,
  VERIFY__BAD_CODE,
  VERIFY__EXPIRED_CODE,
  VERIFY__NO_EMAIL_SENT,

  // USERS
  // Create Profile
  CREATE_PROFILE__SUCCESS,
  CREATE_PROFILE__PROFILE_ALREADY_CREATED,
  CREATE_PROFILE__INVALID_REQUEST,
  CREATE_PROFILE__PHOTO_REQUIRED,

  // Update Profile
  UPDATE_PROFILE__SUCCESS,
  UPDATE_PROFILE__INVALID_REQUEST,

  // Get Profile
  GET_PROFILE__SUCCESS,
  GET_PROFILE__PROFILE_NOT_FOUND,
  GET_PROFILE__BAD_USER_ID,

  // RELATIONSHIPS
  // Get Scene Candidates
  GET_SCENE_CANDIDATES__SUCCESS,
  GET_SCENE_CANDIDATES__INVALID_SCENE,

  // Judge
  JUDGE__SUCCESS,
  JUDGE__CANDIDATE_NOT_FOUND,

  // Block
  BLOCK__SUCCESS,
  BLOCK__USER_NOT_FOUND,

  // Get Matches
  GET_MATCHES__SUCCESS,
  // Update Settings
  UPDATE_SETTINGS__SUCCESS,

  // Get Settings
  GET_SETTINGS__SUCCESS,

  // PHOTOS
  // Sign Url
  SIGN_URL__SUCCESS,

  // Get Photo
  GET_PHOTO__NOT_FOUND,

  // Confirm Upload
  CONFIRM_UPLOAD__SUCCESS,
  CONFIRM_UPLOAD__NO_UNCONFIRMED_PHOTO,
  CONFIRM_UPLOAD__NO_UPLOAD_FOUND,
  CONFIRM_UPLOAD__NO_AVAILABLE_SLOT,

  // Delete Photo
  DELETE_PHOTO__SUCCESS,
  DELETE_PHOTO__CANNOT_DELETE_LAST_PHOTO,
  DELETE_PHOTO__NOT_FOUND,

  // Reorder Photos
  REORDER_PHOTOS__SUCCESS,
  REORDER_PHOTOS__MISMATCHED_IDS,

  // MESSAGES
  // Send Message
  SEND_MESSAGE__SUCCESS,
  SEND_MESSAGE__USER_NOT_FOUND,

  // Get Conversation
  GET_CONVERSATION__SUCCESS,
  GET_CONVERSATION__INVALID_MOST_RECENT_MESSAGE_ID,
};
