// @flow

// SHARED
const SERVER_ERROR = 'SERVER_ERROR';
const BAD_REQUEST = 'BAD_REQUEST';
const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';

// AUTH

// Send Verification Email
const SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND';
const SEND_VERIFICATION_EMAIL__UTLN_NOT_2019 = 'SEND_VERIFICATION_EMAIL__UTLN_NOT_2019';
const SEND_VERIFICATION_EMAIL__EMAIL_SENT = 'SEND_VERIFICATION_EMAIL__EMAIL_SENT';

module.exports = {
  // Shared
  SERVER_ERROR,
  BAD_REQUEST,
  TOO_MANY_REQUESTS,

  // AUTH
  // Register
  SEND_VERIFICATION_EMAIL__UTLN_NOT_FOUND,
  SEND_VERIFICATION_EMAIL__UTLN_NOT_2019,
  SEND_VERIFICATION_EMAIL__EMAIL_SENT,
};
