version: '3.3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker --docker.swarmMode --docker.domain=jumbosmash.localhost --docker.watch --logLevel=DEBUG
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    configs:
      - source: traefik-config
    deploy:
      placement:
        constraints:
          - node.role == manager


  #
  #  Prod Website Service
  #

  website:
    image: sperrys/website:latest
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.tags=website,prod
        - traefik.backend=website
        - traefik.frontend.rule=Host:jumbosmash.localhost
        - traefik.port=80


  #
  #  arthur, (beta) Website Service
  #

  arthur:
    image: sperrys/website
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.tags=website,test
        - traefik.backend=arthur
        - traefik.frontend.rule=Host:arthur.jumbosmash.localhost
        - traefik.port=80

  #
  #  Koh Service
  #

  koh:
    image: sperrys/koh
    ports:
      - 3005:3005
    networks:
      - traefik-net
    environment:
      - development
    deploy:
      labels:
        - traefik.backend=koh
        - traefik.port=3005
        - traefik.frontend.rule=Host:koh.jumbosmash.localhost
        - traefik.backend.loadbalancer.sticky=true

  #
  #  Prod API Service
  #

  server:
    ports:
      - 3001:3000
    environment:
      NODE_ENV: development
    image: sperrys/server:secrets
    secrets:
      - db_pass
      - sendgrid_api_key
      - secret_key
    links:
      - redis # ensures that redis is a host that the container can find
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.backend=server
        - traefik.port=3000
        - traefik.frontend.rule=Host:server.jumbosmash.localhost
        - traefik.backend.loadbalancer.sticky=true

  #
  # redis service
  #

  redis:
    image: redis
    deploy:
      labels:
        - traefik.backend=redis
        - traefik.port=6379
        - traefik.backend.loadbalancer.sticky=true


  #
  #  Deployment Service
  #

  deployment:
    image: "sperrys/deploy:node"
    environment:
      NODE_ENV: production
    ports:
      - 3004:3004
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.backend=deploy
        - traefik.port=3004
        - traefik.frontend.rule=Host:deploy.jumbosmash.localhost

secrets:
  db_pass:
    external: true
  sendgrid_api_key:
    external: true
  secret_key:
    external: true

networks:
  traefik-net:
    driver: overlay
configs:
  traefik-config:
    file: config.toml
